content_template:
  id: deepgreen-chart-bar1
  name: chart-bar
  version: '2.0'
  source: 깔끔이 딥그린.pptx
  source_slide_index: 4
  extracted_at: '2026-01-08T23:29:15.278381'
design_meta:
  quality_score: 8.5
  design_intent: chart-bar
  design_intents:
  - chart-bar
  visual_balance: symmetric
  information_density: medium
canvas:
  reference_width: 1920
  reference_height: 1080
  original_width_emu: !!python/object/new:pptx.util.Emu
  - 12192000
  original_height_emu: !!python/object/new:pptx.util.Emu
  - 6858000
  aspect_ratio: '16:9'
background:
  type: solid
  color: background
shapes:
- id: shape-7
  name: TextBox 6
  type: text_box (17)
  geometry:
    x: 2.88%
    y: 0%
    cx: 41.31%
    cy: 5.05%
  text:
    has_text: true
    alignment: left
    font_size_pt: 12.0
    font_color: '#22523B'
    sample_text: 간략한 설명을 적어주세요.
  z_index: 0
- id: shape-50
  name: TextBox 49
  type: text_box (17)
  geometry:
    x: 2.73%
    y: 0%
    cx: 41.31%
    cy: 7.29%
  text:
    has_text: true
    alignment: left
    font_size_pt: 20.0
    font_color: '#22523B'
    sample_text: 제목을 입력해 주세요.
  z_index: 1
- id: shape-9
  name: 차트 8
  type: chart (3)
  geometry:
    x: 8.39%
    y: 18.81%
    cx: 83.23%
    cy: 74.11%
  z_index: 2
thumbnail: thumbnails/chart/deepgreen-chart-bar1.png
use_for: []
keywords:
- chart-bar
- chart
expected_prompt: chart-bar 슬라이드를 만들어줘.
prompt_keywords:
- chart-bar
- chart
